// mcwp-admin/src/Component/Ipieces/DetailBaseInfoTmp.jsx
import React, { Component } from 'react'; // 引入了React
import { Row, Col } from 'antd';
import pureRender from 'pure-render-decorator';
import { Config } from '../../Config/Index';
import './style/detailBaseInfo.less';

import Idcard from '../../Assets/Images/idcard-detail.png';
import Namecard from '../../Assets/Images/ipieces-tab-face.png';
/**
 * 进件详情基本信息
 * @Author: 魏昌华
 * @Date:   2017-06-26
 * @Last Modified by:   赵俊
 * @Last Modified time: 2017-07-05
 */
class DetailBaseInfo extends Component {
    constructor(props) {
        super(props);
        this.state = {
            pictureInfo:'',
            preview:false,
        }
    }
    personCreditOpen = (personCredit) => {
        personCredit.map((item, index) => {
            window.open(item['srcUrl'])
        })
    }
    previewHide = () => {
        this.setState({
            preview: false
        })
    }
    render() {
        const { baseInfo, personCredit, pictureInfo, showPicture, eduDict, showDetail, hkqs , hkfs , relationship, type } = this.props;
        let loanCustomer = baseInfo.loanCustomer;      // 个人信息
        // let loanPledgeInfoDTO = baseInfo.loanPledgeInfoDTO ; // 抵质押信息
        let basicInfoVerifyDTO = baseInfo.basicInfoVerifyDTO  //验证结果
        let loanSpouse = baseInfo.loanSpouse ;          // 配偶信息
		let loanHomeInfo = baseInfo.loanHomeInfo;      // 家庭信息
        // let maritalStatusText = baseInfo.maritalStatusText;     // 结婚信息
        let loanPledgeInfos = baseInfo.loanPledgeInfos;         //抵质押信息
        let arr = [ 'verified', 'inconsistent', 'unknown', 'unverified' ]  //0核实匹配1核实不匹配2未知3未核实
        return (
            <div className="detail-baseinfo-container">
                <Row className="personal-info">
                    <Col span={4} className='title'>
                        <span id='customer'>个人信息</span>
                    </Col>
                    <Col span={20}>
                        { pictureInfo&&pictureInfo[Config.bizType.loanPerson]&&pictureInfo[Config.bizType.loanPerson].length ? <span className="button" onClick={()=>showPicture(Config.bizType.loanPerson)}>查看文件</span> : '' }
                        {
                            personCredit && personCredit.length?
                            <span className='button' onClick={()=>showPicture('LOAN_PERSON_CREDIT')}>征信报告</span>
                            : null
                        }
                    </Col>
                </Row>
                {/* {
                    loanCustomer ? */}
                        <Row className="personal-info-content" type="flex" justify="start">
                            <Col span={8} className="subtitle">
                                <span>姓名：{loanCustomer && loanCustomer.handInputName || '未录入'}</span>{ type != 5 && type != 8 &&type!=6? <img onClick={showDetail} className="idcard" src={Namecard} alt="身份证" /> : null} 
                                {type!=6?(basicInfoVerifyDTO.cnameVerifyRet == null || basicInfoVerifyDTO.cnameVerifyRet == 3 ? <span className={arr[3]}>未核实</span> : basicInfoVerifyDTO.cnameVerifyRet == 0 ?<span className={"max-width-face-verify " +  arr[basicInfoVerifyDTO.faceVerifyRet || basicInfoVerifyDTO.cnameVerifyRet]}>{basicInfoVerifyDTO.faceVerify || basicInfoVerifyDTO.cnameVerify}</span>:<span className={arr[basicInfoVerifyDTO.cnameVerifyRet ]}>{basicInfoVerifyDTO.cnameVerify}</span>):null}
                            </Col>
                            <Col span={4} className="subtitle">
                                <span>性别：{loanCustomer&&loanCustomer.sex || '未录入'}</span>
                            </Col>
                            <Col span={6} className="subtitle">
                                <span>年龄：{loanCustomer && loanCustomer.age +'岁' || '未录入'}</span>
                            </Col>
                            <Col span={6} className="subtitle">
                                <span>婚姻状况：{loanCustomer && loanCustomer.maritalStatusText || '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>户籍：{loanCustomer&&loanCustomer.censusRegister || '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>学历：{ loanCustomer&&loanCustomer.education && eduDict && eduDict.filter((item,index)=>(item.ddValue==loanCustomer.education))[0] && eduDict.filter((item,index)=>(item.ddValue==loanCustomer.education))[0]['ddText'] || '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>身份证号：{loanCustomer&&loanCustomer.idCardNo || '未录入'}</span><img onClick={()=>showDetail('idcard')} className="idcard" src={Idcard} alt="身份证" />
                                {type!=6?(basicInfoVerifyDTO.customerIdCardVerifyRet ==null || basicInfoVerifyDTO.customerIdCardVerifyRet == 3?<span className={arr[3]}>未核实</span>: <span className={arr[basicInfoVerifyDTO.customerIdCardVerifyRet ]}>{basicInfoVerifyDTO.customerIdCardVerify}</span>):null}
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>申请金额：{loanCustomer&&loanCustomer.applyBalance && loanCustomer.applyBalance + '元' || '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>客户经理预估金额：{loanCustomer&&loanCustomer.estimateAmount && loanCustomer.estimateAmount + '万元' || '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>还款期数：{loanCustomer&&loanCustomer.repaymentPeriod  && hkqs && hkqs.filter((item,index)=>(item.ddValue==loanCustomer.repaymentPeriod))[0] && hkqs.filter((item,index)=>(item.ddValue==loanCustomer.repaymentPeriod))[0]['ddText'] + '期' || '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>还款方式：{loanCustomer&&loanCustomer.repaymentKind && loanCustomer.repaymentKind !=0 ? hkfs && hkfs.filter((item,index)=>(item.ddValue==loanCustomer.repaymentKind))[0] && hkfs.filter((item,index)=>(item.ddValue==loanCustomer.repaymentKind))[0]['ddText']  : '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>总项目资金：{loanCustomer&&loanCustomer.allBalance && loanCustomer.allBalance + '万元' || '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>联系方式：{loanCustomer&&loanCustomer.telephone || '未录入'}</span>
                                {type!=6?(basicInfoVerifyDTO.customerTelVerifyRet ==null || basicInfoVerifyDTO.customerTelVerifyRet == 3?<span className={arr[3]}>未核实</span>: <span className={arr[basicInfoVerifyDTO.customerTelVerifyRet ]}>{basicInfoVerifyDTO.customerTelVerify}</span>):null}
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>户籍住址：{loanCustomer&&loanCustomer.idCardAddr || '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>家庭地址：{loanCustomer&&loanCustomer.homeAddr || '未录入'}</span>
                                {/* <span>家庭地址：{loanCustomer.homeAddr || '未录入'}</span>{basicInfoVerifyDTO.addrVerifyRet ==null || basicInfoVerifyDTO.addrVerifyRet == 3?<span className={arr[3]}>未核实</span>: <span className={arr[basicInfoVerifyDTO.addrVerifyRet ]}>{basicInfoVerifyDTO.addrVerify}</span>} */}
                            </Col>
                        </Row> 
                        {/* :<p className='detail-noInfo'>暂无相关信息</p> */}
                {/* } */}
                <Row className="personal-info">
                    <Col span={4} className="title">
                        <span id='spouse'>直系亲属信息</span>
                    </Col>
                    <Col span={20}>
                        { pictureInfo&&pictureInfo[Config.bizType.loanSpouse]&&pictureInfo[Config.bizType.loanSpouse].length ? <span className="button" onClick={()=>showPicture(Config.bizType.loanSpouse)}>查看文件</span> : '' }
                    </Col>
                </Row>
                {/* {
                    loanSpouse ? */}
                        <Row className="personal-info-content" type="flex" justify="start">
                            <Col span={6} className="subtitle">
                                <span>姓名：{loanSpouse&&loanSpouse.name || '未录入'}</span>
                            </Col>
                            <Col span={6} className="subtitle">
                                <span>性别：{loanSpouse&&loanSpouse.sex || '未录入'}</span>
                            </Col>
                            <Col span={6} className="subtitle">
                                <span>年龄：{loanSpouse&&loanSpouse.age && loanSpouse.age +'岁' || '未录入'}</span>
                            </Col>
                            <Col span={6} className="subtitle">
                                <span>月收入：{loanSpouse&&loanSpouse.income && loanSpouse.income +'元' || '未录入'}</span>
                            </Col>
                            {/* <Col span={12} className="subtitle">
                                <span>单位名称：{loanSpouse.orgName || '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>单位地址：{loanSpouse.orgAddr || '未录入'}</span>
                            </Col>	 */}
                            <Col span={12} className="subtitle">
                                <span>身份证号：{loanSpouse&&loanSpouse.idCardNo || '未录入'}</span>
                                {type!=6?(basicInfoVerifyDTO.spouseIdCardVerifyRet ==null || basicInfoVerifyDTO.spouseIdCardVerifyRet == 3?<span className={arr[3]}>未核实</span>: <span className={arr[basicInfoVerifyDTO.spouseIdCardVerifyRet  ]}>{basicInfoVerifyDTO.spouseIdCardVerify}</span>):null}
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>联系方式：{loanSpouse&&loanSpouse.telephone || '未录入'}</span>
                                {type!=6?(basicInfoVerifyDTO.spouseTelVerifyRet ==null || basicInfoVerifyDTO.spouseTelVerifyRet == 3?<span className={arr[3]}>未核实</span>: <span className={arr[basicInfoVerifyDTO.spouseTelVerifyRet ]}>{basicInfoVerifyDTO.spouseTelVerify}</span>):null}
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>与申请人关系：{loanSpouse&&loanSpouse.relationship  && relationship && relationship.filter((item,index)=>(item.ddValue==loanSpouse.relationship))[0] && relationship.filter((item,index)=>(item.ddValue==loanSpouse.relationship))[0] && relationship.filter((item,index)=>(item.ddValue==loanSpouse.relationship))[0]['ddText'] || '未录入'}</span>
                            </Col>
                            <Col span={12} className="subtitle">
                                <span>学历：{ loanSpouse&&loanSpouse.education && eduDict && eduDict.filter((item,index)=>(item.ddValue==loanSpouse.education))[0] && eduDict.filter((item,index)=>(item.ddValue==loanSpouse.education))[0] && eduDict.filter((item,index)=>(item.ddValue==loanSpouse.education))[0] && eduDict.filter((item,index)=>(item.ddValue==loanSpouse.education))[0]['ddText'] || '未录入'}</span>
                            </Col>
                        </Row> 
                        {/* :<p className='detail-noInfo'>暂无相关信息</p>
                } */}
                <Row className="personal-info">
                    <Col span={4} className="title">
                        <span id='spouse'>紧急联系人信息</span>
                    </Col>
                    <Col span={20}>
                        { pictureInfo&&pictureInfo[Config.bizType.loanEmergency]&&pictureInfo[Config.bizType.loanEmergency].length ? <span className="button" onClick={()=>showPicture(Config.bizType.loanEmergency)}>查看文件</span> : '' }
                    </Col>
                </Row>
                {/* {
                    loanSpouse ? */}
                        <Row className="personal-info-content" type="flex" justify="start">
                            <Col span={6} className="subtitle">
                                <span>姓名：{loanSpouse&&loanSpouse.emergencyContactName  || '未录入'}</span>
                            </Col>
                            <Col span={6} className="subtitle">
                                <span>联系方式：{loanSpouse&&loanSpouse.emergencyContactTelephone  || '未录入'}</span>
                            </Col>
                            <Col span={6} className="subtitle">
                                <span>与申请人关系：{loanSpouse&&loanSpouse.emergencyContactFriendship   && relationship && relationship.filter((item,index)=>(item.ddValue==loanSpouse.emergencyContactFriendship ))[0] && relationship.filter((item,index)=>(item.ddValue==loanSpouse.emergencyContactFriendship ))[0]['ddText'] || '未录入'}</span>
                            </Col>
                        </Row> 
                        {/* :
                        <p className='detail-noInfo'>暂无相关信息</p>
                } */}
                <Row className="personal-info">
                    <Col span={4} className="title">
                        <span>家庭情况信息</span>
                    </Col>
                    <Col span={20}>
                        { pictureInfo&&pictureInfo[Config.bizType.loanFamily]&&pictureInfo[Config.bizType.loanFamily].length ? <span className="button" onClick={()=>showPicture(Config.bizType.loanFamily)}>查看文件</span> : '' }
                    </Col>
                </Row>
                {/* {
                    loanHomeInfo ? */}
                    <Row className="personal-info-content" type="flex" justify="start">
                        <Col span={6} className="subtitle">
                            <span>家庭成员：{loanHomeInfo&&loanHomeInfo.memberNum && loanHomeInfo.memberNum + '个' || '未录入'}</span>
                        </Col>
                        <Col span={6} className="subtitle">
                            <span>供养人数：{loanHomeInfo&&loanHomeInfo.supportNum && loanHomeInfo.supportNum + '个' || '未录入'}</span>
                        </Col>
                        <Col span={6} className="subtitle">
                            <span>家庭每月总收入：{loanHomeInfo&&loanHomeInfo.income && loanHomeInfo.income + '元' || '未录入'}</span>
                        </Col>
                        <Col span={6} className="subtitle">
                            <span>家庭每月总开销：{loanHomeInfo&&loanHomeInfo.totalcost && loanHomeInfo.totalcost + '元' || '未录入'}</span>
                        </Col>
                        <Col span={6} className="subtitle">
                            <span>子女情况：{baseInfo && baseInfo.childrenInfoText || '未录入'}</span>
                        </Col>
                        <Col span={6} className="subtitle">
                            <span>父母情况：{loanHomeInfo&&loanHomeInfo.parentInfo && loanHomeInfo.parentInfo || '未录入'}</span>
                        </Col>
                        <Col span={12} className="subtitle">
                            <Col span={2}>备注：</Col>
                            <Col span={22}>{loanHomeInfo&&loanHomeInfo.remark && loanHomeInfo.remark || '未录入'}</Col>
                        </Col>
                    </Row> 
                    {/* :
                    <p className='detail-noInfo'>暂无相关信息</p>
                } */}
                { loanPledgeInfos ?
                    loanPledgeInfos.map((item, index) => (
                        <div key={index}>
                            <Row className="personal-info">
                                <Col span={4} className="title">
                                    <span id='guarantor'>抵质押{index+1}信息</span>
                                </Col>
                            </Row>
                            <Row className="personal-info-content" type="flex" justify="start">
                                <Col span={6} className="subtitle">
                                    <span>抵质押物名称：{item.pledgeName || '未录入'}</span>
                                </Col>
                                <Col span={6} className="subtitle">
                                    <span>类型：{item.pledgeType ? item.pledgeType == 1 ? '抵押物' : '质押物' : '未录入'}</span>
                                </Col>
                                <Col span={6} className="subtitle">
                                    <span>抵押人姓名：{item.name  || '未录入'}</span>
                                </Col>
                                <Col span={6} className="subtitle">
                                    <span>与申请人关系：{item.relationshipText || '未录入'}</span>
                                </Col>
                                <Col span={6} className="subtitle">
                                    <span>面积：{item.houseSize && item.houseSize + '㎡' || '未录入'}</span>
                                </Col>
                                <Col span={6} className="subtitle">
                                    <span>房龄：{item.houseAge && item.houseAge + '年'  || '未录入'}</span>
                                </Col>
                                <Col span={6} className="subtitle">
                                    <span>评估价值：{item.houseTotal && item.houseTotal + '万元' || '未录入'}</span>
                                </Col>
                                <Col span={12} className="subtitle">
                                    <Col span={12} className="subtitle">
                                        <span>房屋位置：{item.address || '未录入'}</span>
                                    </Col>
                                    <Col span={12} className="subtitle">
                                        <span>权证号：{item.warrentNumber || '未录入'}</span>
                                    </Col>
                                </Col>
                                <Col span={12} className="subtitle">
                                    <span>房屋是否已抵押给其他银行或个人：{item.pledgeStatus ? '是' : '否'}</span>
                                </Col>
                                <Col span={12} className="subtitle">
                                    <Col span={2}>备注：</Col>
                                    <Col span={22}>{item.remark || '未录入'}</Col>
                                </Col>
                            </Row>
                            {/* <Row className="personal-info-content" type="flex" justify="start">

                            </Row>
                            <Row className="personal-info-content" type="flex" justify="start">

                            </Row>
                            <Row className="personal-info-content" type="flex" justify="start">

                            </Row> */}
                        </div>))  : null }
            </div>
        )
    }
}

// 将 store 中的数据作为 props 绑定到 DetailBaseInfo 上
// const mapStateToProps = (state, ownProps) => {
//     let { Common, Ipieces } = state;
//     return {
//         loading: Common.loading
//     }
// }

// // 将 action 作为 props 绑定到 DetailBaseInfo 上。
// const mapDispatchToProps = (dispatch, ownProps) => ({
//     actions: bindActionCreators({ }, dispatch)
// });

// const reduxDetailBaseInfo = connect(mapStateToProps, mapDispatchToProps)(DetailBaseInfo); // 连接redux

const pureDetailBaseInfo = pureRender(DetailBaseInfo);

export default pureDetailBaseInfo;

// mcwp-wap/src/components/ipieces/detailBaseInfoTmp.vue
<template>
  <div>
    <div class="base-container">
      <p id='customer' class="p-title">个人信息<img v-if="personPic && personPic.length" class="title-pic" src="../../assets/base-top-show.png" @click="showPic(Config.bizType.loanPerson, personPic)" /></p>
      <div class="base-content" v-if="loanCustomer">
        <p class="col-p">
          <span class="lable-span">姓名:</span>
          <span class="content-span">{{loanCustomer && loanCustomer.handInputName || '未录入'}}</span>
          <!-- <img v-if="type != 8" @click="showFace=true" class="content-pic" src="../../assets/tab-menber.png"/> -->
          <!-- <span @click="showFace=true" v-if="basicInfoVerifyDTO.cnameVerifyRet == null  || basicInfoVerifyDTO.cnameVerifyRet ==3" class="checkout-result-fail">未核实</span>
          <span v-else-if="basicInfoVerifyDTO.cnameVerifyRet == 0" class="checkout-result-success" :class="{'identical-result': basicInfoVerifyDTO.faceVerifyRet==0 || (!basicInfoVerifyDTO.faceVerifyRet && basicInfoVerifyDTO.cnameVerifyRet == 0 ), 'different-result': basicInfoVerifyDTO.faceVerifyRet}">查看结果
            <Popover class="popover-show">{{basicInfoVerifyDTO.faceVerify || basicInfoVerifyDTO.cnameVerify}}</Popover>
          </span>
          <span v-else class="checkout-result-success different-result">查看结果
            <Popover class="popover-show">{{basicInfoVerifyDTO.cnameVerify}}</Popover>
          </span> -->
        </p>
        <p class="col-p">
          <span class="row-p">
            <span class="lable-span">婚姻状况:</span>
            <span class="content-span">{{loanCustomer.maritalStatusText || '未录入'}}</span>
          </span>
          <span class="row-p">
            <span class="lable-span">年龄:</span>
            <span class="content-span">{{loanCustomer.age && loanCustomer.age + '岁' || '未录入'}}</span>
          </span>
        </p>
        <p class="col-p">
          <!-- <span class="row-p">
            <span class="lable-span">学历:</span>
            <span class="content-span exist-result">{{loanCustomer.education && eduDict && eduDict.filter((item,index)=>(item.ddValue==loanCustomer.education))[0]['ddText'] || '未录入'}}</span>
          </span> -->
          <span class="row-p">
            <span class="lable-span">性别:</span>
            <span class="content-span">{{loanCustomer.sex || '未录入'}}</span>
          </span>
          <span class="row-p">
            <span class="lable-span">学历:</span>
            <span class="content-span exist-result">{{loanCustomer.education && eduDict && eduDict.filter((item,index)=>(item.ddValue==loanCustomer.education))[0]['ddText'] || '未录入'}}</span>
          </span>
        </p>
        <p class="col-p">
          <span class="lable-span">户籍:</span>
          <span class="content-span">{{loanCustomer.censusRegister || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="lable-span">身份证号:</span>
          <span class="content-span">{{loanCustomer.idCardNo || '未录入'}}</span>
          <img @click="showIdCard=true" class="content-pic identity-icon" src="../../assets/identity-icon.png"/>
          <!-- <span v-if="(!basicInfoVerifyDTO.customerIdCardVerifyRet && basicInfoVerifyDTO.customerIdCardVerifyRet != 0) || basicInfoVerifyDTO.customerIdCardVerifyRet==3" class="checkout-result-fail">未核实</span>
          <span v-else class="checkout-result-success" :class="{'identical-result': basicInfoVerifyDTO.customerIdCardVerifyRet==0, 'different-result': basicInfoVerifyDTO.customerIdCardVerifyRet!=0 }">查看结果
            <Popover class="popover-show">{{basicInfoVerifyDTO.customerIdCardVerify}}</Popover>
          </span> -->
        </p>
        <p class="col-p">
          <span class="row-p">
            <span class="lable-span">总项目资金:</span>
            <span class="content-span">{{loanCustomer && loanCustomer.allBalance && loanCustomer.allBalance + '万元' || '未录入'}}</span>
          </span>
          <span class="row-p">
            <span class="lable-span">还款期数:</span>
            <span class="content-span">{{loanCustomer && loanCustomer.repaymentPeriod && hkqs && hkqs.filter((item,index)=>(item.ddValue==loanCustomer.repaymentPeriod))[0]['ddText'] + '期' || '未录入'}}</span>
          </span>
        </p>
        <p class="col-p">
          <span class="lable-span">客户经理预估金额:</span>
          <span class="content-span">{{loanCustomer && loanCustomer.estimateAmount && loanCustomer.estimateAmount + '万元' || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="row-p">
            <span class="lable-span">申请金额:</span>
            <span class="content-span">{{loanCustomer && loanCustomer.applyBalance && loanCustomer.applyBalance + '元' || '未录入'}}</span>
          </span>
          <span class="row-p">
            <span class="lable-span">还款方式:</span>
            <span class="content-span">{{loanCustomer && loanCustomer.repaymentKind && hkfs && hkfs.filter((item,index)=>(item.ddValue==loanCustomer.repaymentKind))[0]['ddText'] || '未录入'}}</span>
          </span>
        </p>
        <p class="col-p">
          <span class="lable-span">联系方式:</span>
          <span class="content-span exist-result">{{loanCustomer.telephone || '未录入'}}</span>
          <!-- <span v-if="(!basicInfoVerifyDTO.customerTelVerifyRet && basicInfoVerifyDTO.customerTelVerifyRet != 0) || basicInfoVerifyDTO.customerTelVerifyRet==3" class="checkout-result-fail">未核实</span>
          <span v-else class="checkout-result-success" :class="{'identical-result': basicInfoVerifyDTO.customerTelVerifyRet==0, 'different-result': basicInfoVerifyDTO.customerTelVerifyRet!=0 }">查看结果
            <Popover class="popover-show">{{basicInfoVerifyDTO.customerTelVerify}}</Popover>
          </span> -->
        </p>
        <p class="col-p">
          <span class="lable-span">户籍住址:</span>
          <span class="content-span">{{loanCustomer.idCardAddr || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="lable-span">家庭地址:</span>
          <span class="content-span">{{loanCustomer.homeAddr || '未录入'}}</span>
          <!-- <span v-if="(!basicInfoVerifyDTO.addrVerifyRet && basicInfoVerifyDTO.addrVerifyRet != 0) || basicInfoVerifyDTO.addrVerifyRet==3" class="checkout-result-fail">未核实</span>
          <span v-else class="checkout-result-success" :class="{'identical-result': basicInfoVerifyDTO.addrVerifyRet==0, 'different-result': basicInfoVerifyDTO.addrVerifyRet!=0 }">查看结果
            <Popover class="popover-show">{{basicInfoVerifyDTO.addrVerify}}</Popover>
          </span> -->
        </p>
      </div>
      <p class="no-data" v-if="!loanCustomer">暂无相关信息</p>
    </div>
    <div class="base-container">
      <p class="p-title">直系亲属信息<img v-if="spousePic && spousePic.length" class="title-pic" src="../../assets/base-top-show.png" @click="showPic(Config.bizType.loanSpouse, spousePic)" /></p>
      <div class="base-content" v-if="loanSpouse">
        <p class="col-p">
          <span class="lable-span">姓名:</span>
          <span class="content-span">{{loanSpouse.name || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="row-p">
            <span class="lable-span">月收入:</span>
            <span class="content-span">{{loanSpouse.income && loanSpouse.income + '元' || '未录入'}}</span>
          </span>
          <span class="row-p">
            <span class="lable-span">性别:</span>
            <span class="content-span">{{loanSpouse.sex || '未录入'}}</span>
          </span>
        </p>
        <p class="col-p">
          <span class="row-p">
            <span class="lable-span">学历:</span>
            <span class="content-span">{{loanSpouse.education && eduDict && eduDict.filter((item,index)=>(item.ddValue==loanSpouse.education))[0]['ddText'] || '未录入'}}</span>
          </span>
          <!-- <span class="row-p">
            <span class="lable-span">年龄:</span>
            <span class="content-span">{{loanSpouse.age && loanSpouse.age + '岁' || '未录入'}}</span>
          </span> -->
        </p>
        <p class="col-p">
          <span class="lable-span">与申请人关系:</span>
          <span class="content-span">{{loanSpouse.relationship   && bcgx && bcgx.filter((item,index)=>(item.ddValue==loanSpouse.relationship ))[0]['ddText'] || '未录入'}}</span>
        </p>
        <!-- <p class="col-p">
          <span class="lable-span">单位名称:</span>
          <span class="content-span">{{loanSpouse.orgName || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="lable-span">单位地址:</span>
          <span class="content-span">{{loanSpouse.orgAddr || '未录入'}}</span>
        </p> -->
        <p class="col-p">
          <span class="lable-span">身份证号:</span>
          <span class="content-span exist-result">{{loanSpouse.idCardNo || '未录入'}}</span>
          <!-- <span v-if="(!basicInfoVerifyDTO.spouseIdCardVerifyRet && basicInfoVerifyDTO.spouseIdCardVerifyRet != 0) || basicInfoVerifyDTO.spouseIdCardVerifyRet==3" class="checkout-result-fail">未核实</span>
          <span v-else class="checkout-result-success" :class="{'identical-result': basicInfoVerifyDTO.spouseIdCardVerifyRet==0, 'different-result': basicInfoVerifyDTO.spouseIdCardVerifyRet!=0 }">查看结果
            <Popover class="popover-show">{{basicInfoVerifyDTO.spouseIdCardVerify}}</Popover>
          </span> -->
        </p>
        <p class="col-p">
          <span class="lable-span">联系方式:</span>
          <span class="content-span exist-result">{{loanSpouse.telephone || '未录入'}}</span>
          <!-- <span v-if="(!basicInfoVerifyDTO.spouseTelVerifyRet && basicInfoVerifyDTO.spouseTelVerifyRet != 0) || basicInfoVerifyDTO.spouseTelVerifyRet==3" class="checkout-result-fail">未核实</span>
          <span v-else class="checkout-result-success" :class="{'identical-result': basicInfoVerifyDTO.spouseTelVerifyRet==0, 'different-result': basicInfoVerifyDTO.spouseTelVerifyRet!=0 }">查看结果
            <Popover class="popover-show">{{basicInfoVerifyDTO.spouseTelVerify}}</Popover>
          </span> -->
        </p>
      </div>
      <p class="no-data" v-if="!loanSpouse">暂无相关信息</p>
    </div>
    <div class="base-container">
      <p class="p-title">紧急联系人信息<img v-if="spousePic && spousePic.length" class="title-pic" src="../../assets/base-top-show.png" @click="showPic(Config.bizType.loanSpouse, spousePic)" /></p>
      <div class="base-content" v-if="loanSpouse">
        <p class="col-p">
          <span class="lable-span">姓名:</span>
          <span class="content-span">{{loanSpouse.emergencyContactName  || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="lable-span">联系方式:</span>
          <span class="content-span">{{loanSpouse.emergencyContactTelephone  || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="lable-span">与申请人关系:</span>
          <span class="content-span">{{loanSpouse.emergencyContactFriendship   && bcgx && bcgx.filter((item,index)=>(item.ddValue==loanSpouse.emergencyContactFriendship ))[0]['ddText'] || '未录入'}}</span>
        </p>
      </div>
      <p class="no-data" v-if="!loanSpouse">暂无相关信息</p>
    </div>
    <div class="base-container">
      <p class="p-title">家庭情况信息<img v-if="familyPic &&　familyPic.length" class="title-pic" src="../../assets/base-top-show.png" @click="showPic(Config.bizType.loanFamily, familyPic)" /></p>
      <div class="base-content" v-if="loanHomeInfo">
        <p class="col-p">
          <span class="lable-span">家庭每月总收入:</span>
          <span class="content-span">{{loanHomeInfo.income && '每月' + loanHomeInfo.income + '元' || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="lable-span">家庭每月总花销:</span>
          <span class="content-span">{{loanHomeInfo.totalcost && '每月' + loanHomeInfo.totalcost + '元' || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="row-p">
            <span class="lable-span">家庭成员:</span>
            <span class="content-span">{{loanHomeInfo.memberNum && loanHomeInfo.memberNum + '个' || '未录入'}}</span>
          </span>
          <span class="row-p">
            <span class="lable-span">供养人数:</span>
            <span class="content-span">{{loanHomeInfo.supportNum && loanHomeInfo.supportNum + '个' || '未录入'}}</span>
          </span>
        </p>
        <p class="col-p">
          <span class="lable-span">子女情况:</span>
          <span class="content-span">{{loanData.childrenInfoText || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="lable-span">父母情况:</span>
          <span class="content-span">{{loanHomeInfo.parentInfo && loanHomeInfo.parentInfo || '未录入'}}</span>
        </p>
        <p class="col-p">
          <span class="lable-span">备注:</span>
          <span class="content-span">{{loanHomeInfo.remark && loanHomeInfo.remark || '未录入'}}</span>
        </p>
      </div>
      <p class="no-data" v-if="!loanHomeInfo">暂无相关信息</p>
    </div>
    <div class="base-container" v-if='loanPledgeInfos && loanPledgeInfos.length'>
      <div v-for='(item, index) in loanPledgeInfos' :key='index'>
        <p class="p-title">抵质押{{index + 1}}信息</p>
        <div class="base-content">
          <p class="col-p">
            <span class="lable-span">抵质押物名称:</span>
            <span class="content-span">{{item.pledgeName || '未录入'}}</span>
          </p>
          <p class="col-p">
            <span class="lable-span">类型:</span>
            <span class="content-span">{{item.pledgeType ? item.pledgeType === 1 ? '抵押物' : '质押物' : '未录入'}}</span>
          </p>
          <p class="col-p">
            <span class="lable-span">抵押人姓名:</span>
            <span class="content-span">{{item.name || '未录入'}}</span>
          </p>
          <p class="col-p">
            <span class="lable-span">与申请人关系:</span>
            <span class="content-span">{{item.relationshipText || '未录入'}}</span>
          </p>
          <p class="col-p">
            <span class="row-p">
              <span class="lable-span">评估价值:</span>
              <span class="content-span">{{item.houseTotal && item.houseTotal + '万元' || '未录入'}}</span>
            </span>
          </p>
          <p class="col-p">
            <span class="row-p">
              <span class="lable-span">面积:</span>
              <span class="content-span">{{item.houseSize && item.houseSize + '㎡' || '未录入'}}</span>
            </span>
            <span class="row-p">
              <span class="lable-span">房龄:</span>
              <span class="content-span">{{item.houseAge && item.houseAge + '年' || '未录入'}}</span>
            </span>
          </p>
          <p class="col-p">
            <span class="lable-span">房屋位置:</span>
            <span class="content-span">{{item.address || '未录入'}}</span>
          </p>
          <p class="col-p">
            <span class="lable-span">权证号:</span>
            <span class="content-span">{{item.warrentNumber || '未录入'}}</span>
          </p>
          <p class="col-p">
            房屋是否已抵押给其他银行或个人:{{item.pledgeStatus ? '是' : '否'}}
          </p>
          <p class="col-p">
            <span class="lable-span">备注:</span>
            <span class="content-span">{{item.remark || '未录入'}}</span>
          </p>
        </div>
      </div>
    </div>
    <div v-transfer-dom>
      <x-dialog v-model="showFace" hide-on-blur :dialog-style="{'max-width': '80%', width: '80%', height: '70%', padding: '.6rem', overflow: 'scroll'}">
        <p v-if="basicInfoVerifyDTO.faceVerifyRet" class="face-title-fail">{{basicInfoVerifyDTO.faceVerify}}</p>
        <p v-else class="face-title">{{basicInfoVerifyDTO.faceVerify}}</p>
        <p class="face-prob">{{loanData.basicInfoVerifyDTO.faceThresholds}}</p>
        <img class="face-result" v-if="picInfo.LOAN_PERSON_IDENTITY_FACE" :src="picInfo.LOAN_PERSON_IDENTITY_FACE[0].srcUrl" alt="人脸识别" />
        <img class="face-result" v-if="picInfo.LOAN_PERSON_IDENTITY_FRONT" :src="picInfo.LOAN_PERSON_IDENTITY_FRONT[0].srcUrl" alt="人脸识别" />
      </x-dialog>
    </div>
    <div v-transfer-dom>
      <x-dialog v-model="showIdCard" hide-on-blur :dialog-style="{'max-width': '80%', width: '80%', height: '70%', padding: '.6rem', overflow: 'scroll'}">
        <p class="card-title">五类证核实：</p>
        <p class="card-title">{{loanData.basicInfoVerifyDTO.identityIegality}}</p>
        <img class="card-result" v-if="picInfo.LOAN_PERSON_IDENTITY_FRONT" :src="picInfo.LOAN_PERSON_IDENTITY_FRONT[0].srcUrl" alt="人脸识别" />
        <img class="card-result" v-if="picInfo.LOAN_PERSON_IDENTITY_BACK" :src="picInfo.LOAN_PERSON_IDENTITY_BACK[0].srcUrl" alt="人脸识别" />
      </x-dialog>
    </div>
  </div>
</template>

<script>
import { XDialog, TransferDom } from 'vux'
import Popover from '../../components/popover.vue'
import Config from '../../config/index'

export default {
  directives: {
    TransferDom
  },
  components: {
    Popover,
    XDialog
  },
  props: ['loanData', 'picInfo', 'popoverShow', 'dictInfo', 'type'],
  data () {
    return {
      basicInfoVerifyDTO: this.loanData.basicInfoVerifyDTO,
      loanCustomer: this.loanData.loanCustomer,
      loanSpouse: this.loanData.loanSpouse,
      loanHomeInfo: this.loanData.loanHomeInfo,
      loanPledgeInfos: this.loanData.loanPledgeInfos,
      maritalStatusText: this.loanData.maritalStatusText,
      Config: Config,
      personPic: this.picInfo[Config.bizType.loanPerson],
      spousePic: this.picInfo[Config.bizType.loanSpouse],
      familyPic: this.picInfo[Config.bizType.loanFamily],
      showFace: false,
      showIdCard: false,
      eduDict: this.dictInfo.education,
      hkqs: this.dictInfo.hkqs,
      bcgx: this.dictInfo.bcgx,
      hkfs: this.dictInfo.hkfs
    }
  },
  methods: {
    showPic (type, PicList) {
      this.$emit('showPic', type, PicList)
    }
  },
  mounted () {
    console.log(this.basicInfoVerifyDTO, 'this.basicInfoVerifyDTO')
    console.log(this.loanData, this.picInfo)
  }
}
</script>

<style lang="less" scoped>
  .base-container{
    width: 10rem;
    margin: 0.26rem auto;
    background: #fff;
    padding-bottom: 0.3rem;
    .p-title{
      border-bottom: 1px solid #e5e5e5;
      height: 1.28rem;
      line-height: 1.28rem;
      font-size: 0.38rem;
      color: #000;
      padding-left: 0.72rem;
      font-weight: bold;
      position: relative;
    }
    .no-data{
      text-align: center;
      padding: 0.3rem;
      font-size: 0.36rem;
    }
    .title-pic{
      position: absolute;
      width: 0.6rem;
      height: 0.6rem;
      top: 0.34rem;
      right: 0.28rem;
    }
    .content-pic{
      margin-top: 0.15rem;
      width: 0.6rem;
      height: 0.6rem;
      margin-left: 0.2rem;
      float: left;
    }
    .p-title::before{
      content: "";
      width: 0.14rem;
      height: 0.42rem;
      background: #369fff;
      border-radius: 8px;
      position: absolute;
      left: 0.4rem;
      top: 0.4rem;
    }
    .base-content{
      padding: 0.6rem 0.7rem;
    }
    .col-p{
      font-size: 0.36rem;
      color: #4f4e4e;
      line-height: 0.86rem;
      // overflow: hidden;
    }
    .col-p::after {
      content: '';
      display: table;
      clear: both;
    }
    .row-p{
      display: block;
      float: left;
      width: 4rem;
    }
    .row-p+.row-p{
      margin-left: 0.48rem;
    }
    .lable-span{
      margin-right: 0.1rem;
      display: block;
      float: left;
      max-width: 60%;
    }
    .content-span{
      display: block;
      float: left;
      max-width: 80%;
    }
    .identity-icon{
      width: 0.44rem;
      height: 0.4rem;
      margin-top: 0.2rem;
    }
    .exist-result{
      max-width: 59%;
    }
    .checkout-result-fail{
      color: #8c8888;
      font-size: 0.28rem;
      background: url(../../assets/checkout-fail.png) no-repeat 0 0.25rem;
      background-size: 0.34rem 0.34rem;
      margin-left: 0.28rem;
      display: block;
      float: left;
      padding-left: 0.46rem;
    }
    .checkout-result-inconsistent{
      color: #f82335;
      font-size: 0.28rem;
      background: url(../../assets/entrymanagement_icon_difference.png) no-repeat 0 0.2rem;
      background-size: 0.34rem 0.34rem;
      margin-left: 0.28rem;
      display: block;
      float: left;
      padding-left: 0.46rem;
    }
    .identical-result {
      background: url(../../assets/checkout-success.png) no-repeat 0 0.2rem;
    }
    .different-result {
      background: url(../../assets/authentication-fail.png) no-repeat 0 0.2rem;
    }
    .checkout-result-success{
      color: #8c8888;
      font-size: 0.28rem;
      background-size: 0.44rem 0.44rem;
      margin-left: 0.28rem;
      display: block;
      float: left;
      padding-left: 0.46rem;
      position: relative;
    }
    .authentication-fail{
      color: #8c8888;
      font-size: 0.28rem;
      background: url(../../assets/authentication-fail.png) no-repeat 0 0.2rem;
      background-size: 0.44rem 0.44rem;
      margin-left: 0.28rem;
      display: block;
      float: left;
      padding-left: 0.46rem;
    }
  }
  .face-title, .card-title {
    font-size: .5rem;
    line-height: .8rem;
    color: #1d1d1d;
  }
  .face-title-fail {
    font-size: .5rem;
    line-height: .8rem;
    color: #f82335;
  }
  .card-title + .card-title {
    margin-bottom: .3rem;
  }
  .face-prob {
    font-size: .3rem;
    color: #313131;
    line-height: .6rem;
    height: .6rem;
    margin-bottom: .3rem;
  }
  .face-result, .card-result {
    width: 100%;
  }
  .face-result + .face-result, .card-result + .card-result {
    margin-top: .8rem;
  }
  .checkout-result-success:hover .popover-show {
    display: block;
  }
   .checkout-result-success .popover-show {
    display: none;
  }
</style>
